/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import com.tplaboratorio.persistencia.*;
import com.tplaboratorio.persistencia.sqliteconnection.SQLiteJDBCDriverConnection;

public class ConnectionTest {
    @Test public void testGetConnection() {
    	SQLiteJDBCDriverConnection conn = new SQLiteJDBCDriverConnection();
    	//assertTrue(SQLiteJDBCDriverConnection.getConnection("") != null);
    	//assertTrue(SQLiteJDBCDriverConnection.getConnection("//*gffggfdf") == null);
    }
}
