/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import com.tplaboratorio.persistencia.*;

public class ConnectionTest {
    @Test public void testSomeLibraryMethod() {
    	
    	assertTrue(SQLiteJDBCDriverConnection.getConnection("") != null);
    }
}
